name: uodate github pages

on:
  push:
    branches:
      - main
    paths:
      - 'run.php' 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP file
        run: php run.php 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Change to match the directory you want to publish to GitHub Pages
